project:
  type: website

website:
  title: "Kayode Hadilou ADJE"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/ahadilou/
      - icon: github
        href: https://github.com/hadilou
      - icon: facebook
        href: https://www.facebook.com/hadilou.adje/
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
